algorithm: fullysupervised
save_dir: ./saved_models/test
save_name: fullysupervised_pollen_0
resume: False
load_path: ./saved_models/test/fullysupervised_pollen_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
use_aim: True
epoch: 4
num_train_iter: 2048
num_eval_iter: 512
num_log_iter: 5
batch_size: 64
eval_batch_size: 64
ema_m: 0.999
crop_ratio: 0.875
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: pollen
train_sampler: RandomSampler
num_workers: 8
world_size: 1
rank: 0
multiprocessing_distributed: False
num_labels: 7000
num_classes: 7
img_size: 200
img_dim: 1